# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wolf/Documents/cPlusPlus/assignment1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wolf/Documents/cPlusPlus/assignment1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wolf/Documents/cPlusPlus/assignment1/CMakeFiles /home/wolf/Documents/cPlusPlus/assignment1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wolf/Documents/cPlusPlus/assignment1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mazer

# Build rule for target.
mazer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mazer
.PHONY : mazer

# fast build rule for target.
mazer/fast:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/build
.PHONY : mazer/fast

src/abGen.o: src/abGen.cpp.o

.PHONY : src/abGen.o

# target to build an object file
src/abGen.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/abGen.cpp.o
.PHONY : src/abGen.cpp.o

src/abGen.i: src/abGen.cpp.i

.PHONY : src/abGen.i

# target to preprocess a source file
src/abGen.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/abGen.cpp.i
.PHONY : src/abGen.cpp.i

src/abGen.s: src/abGen.cpp.s

.PHONY : src/abGen.s

# target to generate assembly for a file
src/abGen.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/abGen.cpp.s
.PHONY : src/abGen.cpp.s

src/bfsSolver.o: src/bfsSolver.cpp.o

.PHONY : src/bfsSolver.o

# target to build an object file
src/bfsSolver.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/bfsSolver.cpp.o
.PHONY : src/bfsSolver.cpp.o

src/bfsSolver.i: src/bfsSolver.cpp.i

.PHONY : src/bfsSolver.i

# target to preprocess a source file
src/bfsSolver.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/bfsSolver.cpp.i
.PHONY : src/bfsSolver.cpp.i

src/bfsSolver.s: src/bfsSolver.cpp.s

.PHONY : src/bfsSolver.s

# target to generate assembly for a file
src/bfsSolver.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/bfsSolver.cpp.s
.PHONY : src/bfsSolver.cpp.s

src/computePath.o: src/computePath.cpp.o

.PHONY : src/computePath.o

# target to build an object file
src/computePath.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/computePath.cpp.o
.PHONY : src/computePath.cpp.o

src/computePath.i: src/computePath.cpp.i

.PHONY : src/computePath.i

# target to preprocess a source file
src/computePath.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/computePath.cpp.i
.PHONY : src/computePath.cpp.i

src/computePath.s: src/computePath.cpp.s

.PHONY : src/computePath.s

# target to generate assembly for a file
src/computePath.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/computePath.cpp.s
.PHONY : src/computePath.cpp.s

src/dfsSolver.o: src/dfsSolver.cpp.o

.PHONY : src/dfsSolver.o

# target to build an object file
src/dfsSolver.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/dfsSolver.cpp.o
.PHONY : src/dfsSolver.cpp.o

src/dfsSolver.i: src/dfsSolver.cpp.i

.PHONY : src/dfsSolver.i

# target to preprocess a source file
src/dfsSolver.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/dfsSolver.cpp.i
.PHONY : src/dfsSolver.cpp.i

src/dfsSolver.s: src/dfsSolver.cpp.s

.PHONY : src/dfsSolver.s

# target to generate assembly for a file
src/dfsSolver.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/dfsSolver.cpp.s
.PHONY : src/dfsSolver.cpp.s

src/dijSolver.o: src/dijSolver.cpp.o

.PHONY : src/dijSolver.o

# target to build an object file
src/dijSolver.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/dijSolver.cpp.o
.PHONY : src/dijSolver.cpp.o

src/dijSolver.i: src/dijSolver.cpp.i

.PHONY : src/dijSolver.i

# target to preprocess a source file
src/dijSolver.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/dijSolver.cpp.i
.PHONY : src/dijSolver.cpp.i

src/dijSolver.s: src/dijSolver.cpp.s

.PHONY : src/dijSolver.s

# target to generate assembly for a file
src/dijSolver.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/dijSolver.cpp.s
.PHONY : src/dijSolver.cpp.s

src/maze.o: src/maze.cpp.o

.PHONY : src/maze.o

# target to build an object file
src/maze.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/maze.cpp.o
.PHONY : src/maze.cpp.o

src/maze.i: src/maze.cpp.i

.PHONY : src/maze.i

# target to preprocess a source file
src/maze.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/maze.cpp.i
.PHONY : src/maze.cpp.i

src/maze.s: src/maze.cpp.s

.PHONY : src/maze.s

# target to generate assembly for a file
src/maze.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/maze.cpp.s
.PHONY : src/maze.cpp.s

src/mazegen.o: src/mazegen.cpp.o

.PHONY : src/mazegen.o

# target to build an object file
src/mazegen.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/mazegen.cpp.o
.PHONY : src/mazegen.cpp.o

src/mazegen.i: src/mazegen.cpp.i

.PHONY : src/mazegen.i

# target to preprocess a source file
src/mazegen.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/mazegen.cpp.i
.PHONY : src/mazegen.cpp.i

src/mazegen.s: src/mazegen.cpp.s

.PHONY : src/mazegen.s

# target to generate assembly for a file
src/mazegen.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/mazegen.cpp.s
.PHONY : src/mazegen.cpp.s

src/mazer.o: src/mazer.cpp.o

.PHONY : src/mazer.o

# target to build an object file
src/mazer.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/mazer.cpp.o
.PHONY : src/mazer.cpp.o

src/mazer.i: src/mazer.cpp.i

.PHONY : src/mazer.i

# target to preprocess a source file
src/mazer.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/mazer.cpp.i
.PHONY : src/mazer.cpp.i

src/mazer.s: src/mazer.cpp.s

.PHONY : src/mazer.s

# target to generate assembly for a file
src/mazer.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/src/mazer.cpp.s
.PHONY : src/mazer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mazer"
	@echo "... src/abGen.o"
	@echo "... src/abGen.i"
	@echo "... src/abGen.s"
	@echo "... src/bfsSolver.o"
	@echo "... src/bfsSolver.i"
	@echo "... src/bfsSolver.s"
	@echo "... src/computePath.o"
	@echo "... src/computePath.i"
	@echo "... src/computePath.s"
	@echo "... src/dfsSolver.o"
	@echo "... src/dfsSolver.i"
	@echo "... src/dfsSolver.s"
	@echo "... src/dijSolver.o"
	@echo "... src/dijSolver.i"
	@echo "... src/dijSolver.s"
	@echo "... src/maze.o"
	@echo "... src/maze.i"
	@echo "... src/maze.s"
	@echo "... src/mazegen.o"
	@echo "... src/mazegen.i"
	@echo "... src/mazegen.s"
	@echo "... src/mazer.o"
	@echo "... src/mazer.i"
	@echo "... src/mazer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

